flight_data:
  outputs:
    dev:
      host: spark-thrift
      method: thrift
      port: 10000
      schema: "{{ env_var('DBT_SCHEMA', 'warehouse') }}"
      threads: 2
      type: spark
      server_side_parameters:
        "spark.databricks.delta.optimizeMetadataQuery.enabled": "false"
  target: dev

spark_lab:
  outputs:
    dev:
      connect_retries: 5
      connect_timeout: 60
      host: spark-thrift
      method: thrift
      port: 10000
      retry_all: true
      schema: warehouse
      threads: 2
      type: spark
      user: jovyan
      server_side_parameters:
        "spark.databricks.delta.optimizeMetadataQuery.enabled": "false"
  target: dev
