sources:
  - name: warehouse
    schema: "{{ target.schema }}"
    tables:
      - name: sample_flight_data
        identifier: sample_flight_data

#      - name: raw_flight
#        identifier: flight_raw
#
#      - name: stage_flight_full
#        identifier: flight
#
#      - name: stage_flight
#        identifier: temp_flight
