FROM apache/hive:4.0.0

USER root
ADD https://jdbc.postgresql.org/download/postgresql-42.7.4.jar /opt/hive/lib/postgresql-42.7.4.jar
RUN chmod 644 /opt/hive/lib/postgresql-42.7.4.jar
RUN apt-get update \
  && apt-get install -y --no-install-recommends --no-install-suggests netcat-openbsd \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /var/cache/apt/*
USER hive
